name: Flora Magnifica
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Flora Magnific
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff0f5'
    - '#a63141'
    - '#b45a5a'
    - '#808a33'
    - '#d78a69'
  brandStrength: 0.5
  lightness: 0.4735050913877785
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
