name: Flora Magnifica
favicon: null
layout_spectrum: 0.4426999478600919
typography_spectrum: 0.8393722902983427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#28272c'
    - '#605252'
    - '#fcfcfa'
    - '#c75b72'
    - '#b9c28b'
  brandStrength: 0.1875
  lightness: 0.4735050913877785
  saturation: 0.375
  rhythmicContrast: 0.2350366914179176
purpose: []
