name: Flora Magnifica
favicon: null
layout_spectrum: 0.4426999478600919
typography_spectrum: 0.8393722902983427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9760085437446833
  lightness: 0.4735050913877785
  saturation: 0.39208424114622176
  rhythmicContrast: 0.2350366914179176
purpose: []
